<footer class="footer-distributed">
    <div class="footer-left">
        <h3>"Company"
        <span>logo</span>
        </h3>
        <p class="footer-links">
            <a href="#">home.</a>
            <a href="#">About.</a>
            <a href="#">Student.</a>
            <a href="#">Teacher.</a>
            <a href="#">Management.</a>
            <a href="#">Contact us.</a>
        </p>
        <p class="footer-company-name">Company Name @ 2018</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker">

            </i>
            <p>
                <span>############</span>
            </p>
        </div>
        <div>
            <i class="fa fa-phone"></i>
            <p>+61424684407</p>
        </div>
        <div>
            <i class="fa fa-envelope">

            </i>
            <p>
                <a href="google.com">haha@gmail.com</a>
            </p>
        </div>
    </div>
    <div class="footer-right">
        <p class="footer-company-about">
            <span>About the company</span>
            ahahahahahahahhahahaahhahahahahahah
            ahahahahahahahahahahahahahahahahaha
            ahhahahahahahahahahahahahahahahahah
        </p>
        <div class="footer-icons">
            <a href="http://www.facebook.com">
                <i class="fa fa-facebook">

                </i>
            </a>
            <a href="http://www.twitter.com">
                <i class="fa fa-twitter">

                </i>
            </a>
            <a href="http://google.com">
                <i class="fa fa-linkedin">

                </i>
            </a>
            <a href="http://github.com">
                <i class="fa fa-github">

                </i>
            </a>
        </div>
    </div>
</footer>
